"""create earthquakes table

Revision ID: dcb97c79af8f
Revises: 9c35c98fc10c
Create Date: 2026-01-12 23:54:08.851940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcb97c79af8f'
down_revision = '9c35c98fc10c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
